task: prim_inference
batch_size: 8
epochs: 400
use_sgd: False
weight_decay_sgd: 1e-4
dp_ratio: 0.5
device: 0
gpu: 0
landmark_type: inference_model_prim
cluster_seed_pts: 256
stage: 1

part_aware: True
mix_style: False
restrict_nei: True
use_uniconv: False

dgcnn_in_feat_dim: 6
use_dgcnn:  True
dgcnn_layers: 3
input_normal: True
backbone: "DGCNN"
inference: True


pnpp_n_layers: 3
debug: False
sampling_tolerance: 5

dataset_root: ./data/traceparts_data
augment: True
if_normal_noise: False
split_type: True
split_train_test: False
train_prim_types: 0,10,1,4 # 1,4,9
test_prim_types: 2,3,9,11 # 2,3,7,0,5,8,6
train_dataset: train_data.txt
val_dataset: val_data.txt
test_dataset: test_data.txt

use_ansi:  True # False
ansi_train_prim_types: 1,3,0 # 1,3,0,4,5 # 1,4,3,6
ansi_val_prim_types: 4,5
ansi_test_prim_types: 2,6 # 0,2,5

test_performance: True

nn_inter_loss:   3 # 3 # 2 # 3
nn_part_level_operations: 4
nn_point_level_feat: 5
nn_feat_transformations: 5



ansi_c_tr_prim_1: 1
ansi_c_tr_prim_2: 0,3
ansi_c_tr_prim_3: 4,5

no_spectral: True
ansi_n_clusters: 7

nn_grp_opers: 4
nn_binary_opers: 6
nn_unary_opers: 6 # 7
nn_in_feats: 7

v2_tree: True # False

in_model_loss_model: False

lr_scaler: 1

init_lr: 0.001
weight_decay: 1e-4
lr_decay_ratio: 0.7
step_size: 30
num_points: 10000
num_points_sampled_for_seed: 512
feat_dims: 32,64,128
up_feat_dims: 64,32,32
n_samples: 1024,512,1
radius: 0.2,0.4,0.4
k: 48
pred_nmasks: 30
n_max_instances: 24
map_feat_dim: 32
nseeds: 256
add_intermediat_loss: False
seg_nmasks: 11
n_primitives: 4
nmasks: 11
n_layers:  3 # 6
local_unet_n_layers:  3 # 6
in_feat_dim: 3
use_normal_loss: True

resume: "./ckpts/Loss_last_saved_model.pth"

cls_backbone: True
with_normal: True
with_conf_loss: False # True
use_spfn: True # False #ue # False # True
with_fitting_loss: False # True # False
with_primpred_loss: False # True
with_normalcst_loss: False # True
with_parampred_loss: False # True
param_weight: 0.1
param_pred_dim: 22
n_samples_inter_loss: 10000

sea_interval: 7


conv_select_types: 0,0,0 # 0,0,0,0,0,0
point_feat_selection: 6 # 25 # 6 # 25
point_geo_feat_selection: 5
contrast_selection: 1,1,1
